# Generated by Django 4.1.2 on 2022-11-22 06:59

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('JAN-MAR 2022', 'JAN-MAR 2022'), ('APR-JUN 2022', 'APR-JUN 2022'), ('JULY-AUG 2022', 'JULY-AUG 2022')], max_length=255, null=True)),
                ('package', models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('transport_facility', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('JAN-MAR 2022', 'JAN-MAR 2022'), ('APR-JUN 2022', 'APR-JUN 2022'), ('JULY-AUG 2022', 'JULY-AUG 2022')], max_length=255, null=True)),
                ('package', models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('date_of_notification', models.DateField(auto_now=True)),
                ('action_taken', models.CharField(blank=True, choices=[('Agreed for rehabilation', 'Agreed for rehabilation'), ('Agreed For Compensation', 'Agreed For Compensation'), ('Not agreed', 'Not agreed')], max_length=100, null=True)),
                ('Compensation_offered', models.CharField(blank=True, choices=[('Alternate accommodation / Commercial Unit', 'Alternate accommodation / Commercial Unit'), ('Cash Compensation', 'Cash compensation'), ('Land Provided Area', 'Land Provided Area')], max_length=255, null=True)),
                ('eligibility_status', models.BooleanField()),
                ('category_of_PAP', models.CharField(blank=True, choices=[('individual', 'individual'), ('commercial', 'commercial'), ('land', 'land'), ('Institutional', 'Institutional'), ('other', 'other')], max_length=255, null=True)),
                ('Ownership_status', models.CharField(blank=True, choices=[('structure', 'structure'), ('land', 'land'), ('Both', 'Both')], max_length=255, null=True)),
                ('legal_status', models.CharField(blank=True, choices=[('legal', 'legal'), ('under dispute', 'under dispute'), ('illegal', 'illegal')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='social_Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_monitoring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rehabilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifting_allowance', models.BooleanField()),
                ('livelihood_support', models.CharField(blank=True, max_length=255, null=True)),
                ('traning', models.BooleanField()),
                ('tenaments', models.BooleanField()),
                ('transport_allowance', models.BooleanField()),
                ('additional_financial_support_or_revolving_fund', models.BooleanField()),
                ('Community_engagement', models.CharField(blank=True, max_length=255, null=True)),
                ('rehabilation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rehabilation', to='SocialMonitoring.pap')),
            ],
        ),
        migrations.AddField(
            model_name='pap',
            name='pap_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PAPs', to='SocialMonitoring.social_monitoring'),
        ),
        migrations.CreateModel(
            name='LabourCampDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('JAN-MAR 2022', 'JAN-MAR 2022'), ('APR-JUN 2022', 'APR-JUN 2022'), ('JULY-AUG 2022', 'JULY-AUG 2022')], max_length=255, null=True)),
                ('package', models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('toilets', models.BooleanField()),
                ('Drinking_water', models.BooleanField()),
                ('demarking_of_pathways', models.BooleanField()),
                ('signAges_or_labeling', models.BooleanField()),
                ('Medical_facility', models.CharField(blank=True, choices=[('Regular Health Checkup', 'Regular Health Checkup'), ('Availability Of Doctor', 'Availability Of Doctor'), ('Availability Of First aid Kit', 'Availability Of Firstaid Kit')], max_length=255, null=True)),
                ('kitchen_area', models.BooleanField()),
                ('fire_execution', models.BooleanField()),
                ('segregation_of_waste', models.BooleanField()),
                ('rooms_or_doms', models.CharField(blank=True, max_length=255, null=True)),
                ('labourcamp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labourcampdetails', to='SocialMonitoring.labourcamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='labourcamp',
            name='camp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_camp', to='SocialMonitoring.social_monitoring'),
        ),
        migrations.CreateModel(
            name='ConstructionSiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('JAN-MAR 2022', 'JAN-MAR 2022'), ('APR-JUN 2022', 'APR-JUN 2022'), ('JULY-AUG 2022', 'JULY-AUG 2022')], max_length=255, null=True)),
                ('package', models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('site_photographs', models.ImageField(blank=True, null=True, upload_to='')),
                ('demarking_of_pathways', models.BooleanField()),
                ('signAges_or_labeling', models.BooleanField()),
                ('Medical_facility', models.CharField(choices=[('Regular Health Checkup', 'Regular Health Checkup'), ('Availability Of Doctor', 'Availability Of Doctor'), ('Availability Of First aid Kit', 'Availability Of Firstaid Kit')], max_length=255)),
                ('Drinking_water', models.BooleanField()),
                ('Toilet_facility', models.BooleanField()),
                ('construction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructioncamp', to='SocialMonitoring.labourcamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alternate_accommodation_or_Commercial_Unit', models.FileField(blank=True, null=True, upload_to='')),
                ('cash_compensation', models.CharField(blank=True, max_length=255, null=True)),
                ('land_provided_area', models.CharField(blank=True, max_length=255, null=True)),
                ('Compensation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Compensation', to='SocialMonitoring.pap')),
            ],
        ),
    ]
