# Generated by Django 4.1.2 on 2022-11-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pap',
            name='date_of_notification',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
