# Generated by Django 4.1.2 on 2022-12-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pap',
            name='compensationStatus',
            field=models.CharField(blank=True, choices=[('Cash Compensation', 'Cash Compensation'), ('Land Provided Area', 'Land Provided Area'), ('Alternate accommodation / Commercial Unit', 'Alternate accommodation / Commercial Unit')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='isfinancialSupport',
            field=models.BooleanField(blank=True),
        ),
    ]
