# Generated by Django 4.1.2 on 2022-11-22 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0004_alter_pap_date_of_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pap',
            name='date_of_notification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 12, 42, 26, 531844), null=True),
        ),
    ]
