# Generated by Django 4.1.2 on 2022-11-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0006_remove_pap_date_of_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='date_of_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
