# Generated by Django 4.1.2 on 2022-11-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0008_remove_constructionsitedetails_medical_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcamp',
            name='transport_facility',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
