# Generated by Django 4.1.2 on 2022-11-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0009_alter_labourcamp_transport_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcampdetails',
            name='labourcamp_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labourcampdetails', to='SocialMonitoring.labourcamp'),
        ),
    ]
