# Generated by Django 4.1.2 on 2022-11-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0010_alter_labourcampdetails_labourcamp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcampdetails',
            name='labourcamp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labourcampdetails', to='SocialMonitoring.labourcamp'),
        ),
    ]
