# Generated by Django 4.1.2 on 2022-11-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0011_alter_labourcampdetails_labourcamp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='demarking_of_pathways',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='signAges_or_labeling',
            field=models.BooleanField(blank=True),
        ),
    ]
