# Generated by Django 4.1.2 on 2022-11-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0012_alter_constructionsitedetails_demarking_of_pathways_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='Drinking_water',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='Toilet_facility',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='Availability_Of_Doctor',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='Availability_Of_First_aid_Kit',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='Drinking_water',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='Regular_Health_Checkup',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='demarking_of_pathways',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='fire_execution',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='kitchen_area',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='segregation_of_waste',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='signAges_or_labeling',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='labourcampdetails',
            name='toilets',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rehabilation',
            name='shifting_allowance',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rehabilation',
            name='tenaments',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rehabilation',
            name='traning',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='rehabilation',
            name='transport_allowance',
            field=models.BooleanField(blank=True),
        ),
    ]
