# Generated by Django 4.1.2 on 2022-11-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0013_alter_constructionsitedetails_drinking_water_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcamp',
            name='transport_facility',
            field=models.BooleanField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
