# Generated by Django 4.1.2 on 2022-11-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0014_alter_labourcamp_transport_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourcamp',
            name='transport_facility',
        ),
    ]
