# Generated by Django 4.1.2 on 2022-12-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0016_rename_construction_id_constructionsitedetails_labourcamp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pap',
            name='pap_id',
        ),
        migrations.DeleteModel(
            name='social_Monitoring',
        ),
    ]
