# Generated by Django 4.1.2 on 2022-12-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0017_remove_pap_pap_id_delete_social_monitoring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensation',
            old_name='Compensation_id',
            new_name='PAP_id',
        ),
        migrations.RenameField(
            model_name='rehabilation',
            old_name='rehabilation_id',
            new_name='PAP_id',
        ),
    ]
