# Generated by Django 4.1.2 on 2022-12-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastetreatments',
            old_name='waste_handled_details',
            new_name='wasteHandlingLocation',
        ),
        migrations.RenameField(
            model_name='wastetreatments',
            old_name='waste_handled',
            new_name='wastehandling',
        ),
        migrations.RenameField(
            model_name='wastetreatments',
            old_name='waste_type',
            new_name='wastetype',
        ),
    ]
