# Generated by Django 4.1.2 on 2022-11-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0002_alter_treemanagment_tree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsourcing',
            name='materialsourcing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MaterialSourcing', to='EnvMonitoring.envmonitoring'),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='tree_id',
            field=models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnvironmentalMonitoring', to='EnvMonitoring.envmonitoring'),
        ),
        migrations.AlterField(
            model_name='wastetreatments',
            name='waste_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_treatments', to='EnvMonitoring.envmonitoring'),
        ),
    ]
