# Generated by Django 4.1.2 on 2022-11-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0003_alter_materialsourcing_materialsourcing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsourcing',
            name='approvals',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='tree_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnvironmentalMonitoring', to='EnvMonitoring.envmonitoring'),
        ),
    ]
