# Generated by Django 4.1.2 on 2022-12-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0003_rename_package_air_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialsourcing',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialsourcing',
            name='sourceOfQuarry',
            field=models.CharField(blank=True, choices=[('Mines', 'Mines'), ('Blast', 'Blast')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noise',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wastetreatments',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
