# Generated by Django 4.1.2 on 2022-11-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0004_alter_materialsourcing_approvals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envmonitoring',
            old_name='env_quality_monitoring',
            new_name='env_monitoring',
        ),
        migrations.AlterField(
            model_name='envqualitymonitoring',
            name='eqm_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='EnvQualityMonitoring', to='EnvMonitoring.envmonitoring'),
        ),
    ]
