# Generated by Django 4.1.2 on 2022-12-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0004_alter_air_date_alter_materialsourcing_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air',
            old_name='date',
            new_name='dateOfConduct',
        ),
        migrations.RenameField(
            model_name='materialsourcing',
            old_name='date',
            new_name='dateOfConduct',
        ),
        migrations.RenameField(
            model_name='noise',
            old_name='date',
            new_name='dateOfConduct',
        ),
        migrations.RenameField(
            model_name='treemanagment',
            old_name='date',
            new_name='dateOfConduct',
        ),
        migrations.RenameField(
            model_name='wastetreatments',
            old_name='date',
            new_name='dateOfConduct',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='date',
            new_name='dateOfConduct',
        ),
        migrations.AlterField(
            model_name='air',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Jan-Mar 2022', 'Jan-Mar 2022'), ('Apr-Jun 2022', 'Apr-Jun 2022'), ('July-Aug 2022', 'July-Aug 2022')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialsourcing',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Jan-Mar 2022', 'Jan-Mar 2022'), ('Apr-Jun 2022', 'Apr-Jun 2022'), ('July-Aug 2022', 'July-Aug 2022')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noise',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Jan-Mar 2022', 'Jan-Mar 2022'), ('Apr-Jun 2022', 'Apr-Jun 2022'), ('July-Aug 2022', 'July-Aug 2022')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Jan-Mar 2022', 'Jan-Mar 2022'), ('Apr-Jun 2022', 'Apr-Jun 2022'), ('July-Aug 2022', 'July-Aug 2022')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wastetreatments',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Jan-Mar 2022', 'Jan-Mar 2022'), ('Apr-Jun 2022', 'Apr-Jun 2022'), ('July-Aug 2022', 'July-Aug 2022')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Jan-Mar 2022', 'Jan-Mar 2022'), ('Apr-Jun 2022', 'Apr-Jun 2022'), ('July-Aug 2022', 'July-Aug 2022')], max_length=255, null=True),
        ),
    ]
