# Generated by Django 4.1.2 on 2022-12-01 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnvMonitoring', '0005_rename_env_quality_monitoring_envmonitoring_env_monitoring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='air_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airs', to='EnvMonitoring.envqualitymonitoring'),
        ),
        migrations.AlterField(
            model_name='envmonitoring',
            name='env_monitoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quality_Monitoring', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='envqualitymonitoring',
            name='eqm_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EnvQualityMonitoring', to='EnvMonitoring.envmonitoring'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='noise_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noises', to='EnvMonitoring.envqualitymonitoring'),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waters', to='EnvMonitoring.envqualitymonitoring'),
        ),
    ]
