# Generated by Django 4.1.2 on 2022-12-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0006_rename_cutting_details_treemanagment_botanicalname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treemanagment',
            old_name='planted_details',
            new_name='plantedDetails',
        ),
    ]
