# Generated by Django 4.1.2 on 2022-11-15 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_report_user_is_consultant_user_is_contractor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvQualityMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnvQualityMonitoring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.DurationField()),
                ('package', models.CharField(max_length=255)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('date', models.DateField(blank=True, default=None)),
                ('quality_of_water', models.CharField(max_length=255)),
                ('source_of_water', models.CharField(max_length=255)),
                ('water_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.envqualitymonitoring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.DurationField()),
                ('package', models.CharField(max_length=255)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('date', models.DateField(blank=True, default=None)),
                ('details', models.CharField(max_length=255)),
                ('noise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.envqualitymonitoring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_quality_monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quality_Monitoring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.DurationField()),
                ('package', models.CharField(max_length=255)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('date', models.DateField(blank=True, default=None)),
                ('standard', models.FloatField(max_length=255)),
                ('deviation', models.FloatField(max_length=255)),
                ('trends', models.CharField(max_length=100)),
                ('air_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.envqualitymonitoring')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
