# Generated by Django 4.1.2 on 2022-11-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_envqualitymonitoring_water_noise_envmonitoring_air'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='quarter',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='noise',
            name='quarter',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='water',
            name='quarter',
            field=models.CharField(max_length=255),
        ),
    ]
