# Generated by Django 4.1.2 on 2022-11-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_air_date_alter_noise_date_alter_water_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='photographs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='envqualitymonitoring',
            name='eqm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnvQualityMonitoring', to='Auth.envmonitoring'),
        ),
    ]
