# Generated by Django 4.1.2 on 2022-11-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_envqualitymonitoring_eqm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envqualitymonitoring',
            name='eqm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnvQualityMonitoring', to='Auth.envmonitoring'),
        ),
    ]
