# Generated by Django 4.1.2 on 2022-11-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_wastetreatments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('approvals', models.FileField(null=True, upload_to='')),
                ('source_of_quary', models.CharField(choices=[('Mines', 'Mines'), ('Blast', 'Blast')], max_length=255)),
                ('materialsourcing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaterialSourcing', to='Auth.envmonitoring')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
