# Generated by Django 4.1.2 on 2022-11-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_wastetreatments_waste_handled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastetreatments',
            name='waste_handled',
            field=models.CharField(blank=True, choices=[('disposal', 'disposal'), ('Dumped', 'Dumped'), ('Transported to another location', 'Transported to another location'), ('recycle', 'recycle')], max_length=255, null=True),
        ),
    ]
