# Generated by Django 4.1.2 on 2022-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_alter_wastetreatments_waste_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastetreatments',
            name='waste_handled_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='deviation',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='standard',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='trends',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noise',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='Cutting_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='Management',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='No_of_trees_cut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='planted_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='transplanted_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='quality_of_water',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='source_of_water',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
