# Generated by Django 4.1.2 on 2022-11-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_wastetreatments_waste_handled_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noise',
            old_name='details',
            new_name='noise_level',
        ),
        migrations.AddField(
            model_name='noise',
            name='Monitoring_Period',
            field=models.CharField(blank=True, choices=[('1 hour', '1 hour'), ('3 hours', '3 hours'), ('6 hours', '6 hours')], max_length=255, null=True),
        ),
    ]
