# Generated by Django 4.1.2 on 2022-11-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0018_alter_air_date_alter_air_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographs',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='photographs',
            name='incharge_person',
            field=models.CharField(blank=True, max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='photographs',
            name='photographs_clcik_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photographs',
            name='site_photographs',
            field=models.ImageField(blank=True, null=True, upload_to='site_photographs/'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
