# Generated by Django 4.1.2 on 2022-11-19 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0019_photographs_date_photographs_incharge_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='traning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('traning_title', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_attends', models.IntegerField(blank=True, null=True)),
                ('incharge_person', models.CharField(blank=True, max_length=253, null=True)),
                ('conduct_date', models.DateField(auto_now=True, null=True)),
                ('traning_date', models.DateField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('photographs', models.ImageField(blank=True, null=True, upload_to='traning_photographs/')),
                ('traning_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
