# Generated by Django 4.1.2 on 2022-11-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0020_traning'),
    ]

    operations = [
        migrations.AddField(
            model_name='traning',
            name='female',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traning',
            name='male',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traning',
            name='traninig_initiated_by',
            field=models.CharField(blank=True, choices=[('GC (Genral Contractor)', 'GC (Genral Contractor)'), ('Consultant', 'Consultant'), ('MMRDA', 'MMRDA')], max_length=255, null=True),
        ),
    ]
