# Generated by Django 4.1.2 on 2022-11-21 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0021_traning_female_traning_male_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('JAN-MAR 2022', 'JAN-MAR 2022'), ('APR-JUN 2022', 'APR-JUN 2022'), ('JULY-AUG 2022', 'JULY-AUG 2022')], max_length=255, null=True)),
                ('package', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('date_of_notification', models.DateField(auto_now=True)),
                ('action_taken', models.CharField(blank=True, choices=[('Agreed for rehabilation', 'Agreed for rehabilation'), ('Agreed For Compensation', 'Agreed For Compensation'), ('Not agreed', 'Not agreed')], max_length=100, null=True)),
                ('Compensation_offered', models.CharField(blank=True, choices=[('Alternate accommodation / Commercial Unit', 'Alternate accommodation / Commercial Unit'), ('Cash Compensation', 'Cash compensation'), ('Land Provided Area', 'Land Provided Area')], max_length=255, null=True)),
                ('eligibility_status', models.BooleanField()),
                ('Ownership_status', models.CharField(blank=True, choices=[('structure', 'structure'), ('land', 'land'), ('Both', 'Both')], max_length=255, null=True)),
                ('category_of_PAP', models.CharField(blank=True, choices=[('individual', 'individual'), ('commercial', 'commercial'), ('land', 'land'), ('Institutional', 'Institutional'), ('other', 'other')], max_length=255, null=True)),
                ('legal_status', models.CharField(blank=True, choices=[('legal', 'legal'), ('under dispute', 'under dispute'), ('illegal', 'illegal')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='date_of_incoident',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='nature_of_accident',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='photographs',
            field=models.ImageField(blank=True, null=True, upload_to='photographs/'),
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupationalHealthSafety', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='social_Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_monitoring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rehabilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifting_allowance', models.BooleanField()),
                ('livelihood_support', models.CharField(blank=True, max_length=255, null=True)),
                ('traning', models.BooleanField()),
                ('tenaments', models.BooleanField()),
                ('transport_allowance', models.BooleanField()),
                ('additional_financial_support_or_revolving_fund', models.BooleanField()),
                ('Community_engagement', models.CharField(blank=True, max_length=255, null=True)),
                ('rehabilation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auth.pap')),
            ],
        ),
        migrations.AddField(
            model_name='pap',
            name='pap_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PAPs', to='Auth.social_monitoring'),
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alternate_accommodation_or_Commercial_Unit', models.FileField(blank=True, null=True, upload_to='')),
                ('cash_compensation', models.CharField(blank=True, max_length=255, null=True)),
                ('land_provided_area', models.CharField(blank=True, max_length=255, null=True)),
                ('Compensation_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Compensation', to='Auth.pap')),
            ],
        ),
    ]
