# Generated by Django 4.1.2 on 2022-11-21 09:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0022_pap_alter_occupationalhealthsafety_date_of_incoident_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='air',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='materialsourcing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='materialsourcing',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='noise',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='noise',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='wastetreatments',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='wastetreatments',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='water',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='water',
            name='longitude',
        ),
        migrations.AddField(
            model_name='air',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='materialsourcing',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='noise',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pap',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='wastetreatments',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='water',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='air',
            name='package',
            field=models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialsourcing',
            name='package',
            field=models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noise',
            name='package',
            field=models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='package',
            field=models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='package',
            field=models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='package',
            field=models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LabourCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('JAN-MAR 2022', 'JAN-MAR 2022'), ('APR-JUN 2022', 'APR-JUN 2022'), ('JULY-AUG 2022', 'JULY-AUG 2022')], max_length=255, null=True)),
                ('package', models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('transport_facility', models.BooleanField()),
                ('camp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_camp', to='Auth.social_monitoring')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='constructionsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('JAN-MAR 2022', 'JAN-MAR 2022'), ('APR-JUN 2022', 'APR-JUN 2022'), ('JULY-AUG 2022', 'JULY-AUG 2022')], max_length=255, null=True)),
                ('package', models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('site_photographs', models.ImageField(blank=True, null=True, upload_to='')),
                ('demarking_of_pathways', models.BooleanField()),
                ('signAges_or_labeling', models.BooleanField()),
                ('Drinking_water', models.BooleanField()),
                ('Toilet_facility', models.BooleanField()),
                ('construction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructioncamp', to='Auth.labourcamp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
