# Generated by Django 4.1.2 on 2022-11-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0023_remove_air_latitude_remove_air_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envmonitoring',
            name='env_quality_monitoring',
        ),
        migrations.RemoveField(
            model_name='envqualitymonitoring',
            name='eqm_id',
        ),
        migrations.RemoveField(
            model_name='materialsourcing',
            name='materialsourcing_id',
        ),
        migrations.RemoveField(
            model_name='noise',
            name='noise_id',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='wastetreatments',
            name='waste_id',
        ),
        migrations.RemoveField(
            model_name='water',
            name='water_id',
        ),
        migrations.DeleteModel(
            name='Air',
        ),
        migrations.DeleteModel(
            name='EnvMonitoring',
        ),
        migrations.DeleteModel(
            name='EnvQualityMonitoring',
        ),
        migrations.DeleteModel(
            name='MaterialSourcing',
        ),
        migrations.DeleteModel(
            name='Noise',
        ),
        migrations.DeleteModel(
            name='TreeManagment',
        ),
        migrations.DeleteModel(
            name='WasteTreatments',
        ),
        migrations.DeleteModel(
            name='water',
        ),
    ]
