# Generated by Django 4.1.2 on 2022-11-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0024_remove_envmonitoring_env_quality_monitoring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsite',
            name='construction_id',
        ),
        migrations.RemoveField(
            model_name='labourcamp',
            name='camp_id',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='pap_id',
        ),
        migrations.RemoveField(
            model_name='rehabilation',
            name='rehabilation_id',
        ),
        migrations.RemoveField(
            model_name='social_monitoring',
            name='sm_id',
        ),
        migrations.DeleteModel(
            name='Compensation',
        ),
        migrations.DeleteModel(
            name='constructionsite',
        ),
        migrations.DeleteModel(
            name='LabourCamp',
        ),
        migrations.DeleteModel(
            name='PAP',
        ),
        migrations.DeleteModel(
            name='Rehabilation',
        ),
        migrations.DeleteModel(
            name='social_Monitoring',
        ),
    ]
