# Generated by Django 4.1.2 on 2022-11-23 06:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0025_remove_constructionsite_construction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='incident_issuer',
            new_name='joining_medical_check',
        ),
        migrations.RenameField(
            model_name='photographs',
            old_name='site_name',
            new_name='photograph_title',
        ),
        migrations.RenameField(
            model_name='photographs',
            old_name='photographs_clcik_by',
            new_name='photographs_uploaded_by',
        ),
        migrations.RemoveField(
            model_name='occupationalhealthsafety',
            name='date_of_incoident',
        ),
        migrations.RemoveField(
            model_name='occupationalhealthsafety',
            name='medical_check',
        ),
        migrations.RemoveField(
            model_name='photographs',
            name='incharge_person',
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='collective_majors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='date_of_incident',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='incident_reporting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='type_of_incident',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photographs',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
