# Generated by Django 4.1.2 on 2022-11-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0027_alter_user_options_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
