# Generated by Django 4.1.2 on 2022-11-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0028_alter_user_options_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
