# Generated by Django 4.1.2 on 2022-11-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0030_alter_user_options_user_first_name_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupationalhealthsafety',
            name='user',
        ),
        migrations.DeleteModel(
            name='photographs',
        ),
        migrations.DeleteModel(
            name='report',
        ),
        migrations.RemoveField(
            model_name='traning',
            name='traning_id',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.DeleteModel(
            name='occupationalHealthSafety',
        ),
        migrations.DeleteModel(
            name='traning',
        ),
    ]
