# Generated by Django 4.1.2 on 2022-11-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0033_user_first_name_user_last_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
