# Generated by Django 4.1.2 on 2022-12-12 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0036_remove_user_permissionsmixin_ptr_user_groups_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
