# Generated by Django 4.1.2 on 2022-12-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographs',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
