# Generated by Django 4.1.2 on 2022-12-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0002_alter_photographs_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('messsage', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
